### ISSUE TITLE
Exception: pymysql.err.InterfaceError: (0, '')

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#170]
```
2017-08-08T09:06:29-0700 [ims.dms._dms.DutyManagementSystem#info] Retrieving personnel from Duty Management System...
2017-08-08T09:06:29-0700 [_GenericHTTPChannelProtocol,99,127.0.0.1] Rollback failed
        Traceback (most recent call last):
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
            result = inContext.theWork()
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
            inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 474, in _runInteraction
            conn.rollback()
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/enterprise/adbapi.py", line 52, in rollback
            self._connection.rollback()
          File "/opt/ims/lib/env/lib/python3.6/site-packages/pymysql/connections.py", line 792, in rollback
            self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
          File "/opt/ims/lib/env/lib/python3.6/site-packages/pymysql/connections.py", line 1071, in _execute_command
            raise err.InterfaceError("(0, '')")
        pymysql.err.InterfaceError: (0, '')
```

**Comment by wsanchez** [comment]
I'm guessing this is what happens when the MySQL connection hiccups, and I think that happened last year also.  This may not be a big deal…
