### ISSUE TITLE
Exception: ims.store._exceptions.StorageError: UNIQUE constraint failed: EVENT_ACCESS.EVENT, EVENT_ACCESS.EXPRESSION

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#172]
```
2017-08-07T19:21:40-0700 [ims.store.sqlite._store.DataStore#critical] Unable to set write access for 2017: UNIQUE constraint failed: EVENT_ACCESS.EVENT, EVENT_ACCESS.EXPRESSION
2017-08-07T19:21:40-0700 [ims.application._klein#critical] Request failed
        Traceback (most recent call last):
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 126, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 211, in _f
            return _call(instance, f, request, *a, **kw)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 51, in _call
            result = ensureDeferred(result)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 908, in ensureDeferred
            return _inlineCallbacks(None, coro, Deferred())
        --- <exception caught here> ---
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_api.py", line 799, in editAdminAccessResource
            await storage.setWriters(event, acl["writers"])
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 432, in setWriters
            return self._setEventAccess(event, "write", writers)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 386, in _setEventAccess
            raise StorageError(e)
        ims.store._exceptions.StorageError: UNIQUE constraint failed: EVENT_ACCESS.EVENT, EVENT_ACCESS.EXPRESSION
```

**Comment by wsanchez** [comment]
Pretty sure this happens when entering a duplicate entry into the ACL for an event.  Since that's a management feature, and rarely used, not a show stopper.

**Comment by srabraham** [comment]
The UI no longer seems to allow creating duplicate entries in the first place, and it would be appropriate for an error to be logged if a constraint were at risk. Close?
