### ISSUE TITLE
builtins.TypeError: __init__() missing 1 required positional argument: 'retry'

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#185]
This happened while I was attaching incident reports to an incident:

```
2017-08-12T13:28:50-0700 [ims.store.sqlite._store.DataStore#info] Created report entry: 2017-08-12 20:28:50.513464+00:00 Tool*: Changed state to: closed
2017-08-12T13:28:50-0700 [ims.store.sqlite._store.DataStore#info] Attached report entries to incident Test#91: (ReportEntry(created=datetime.datetime(2017, 8, 12, 20, 28, 50, 513464, tzinfo=datetime.timezone.utc), author='Tool', automatic=True, text='Changed state to: closed'),)
2017-08-12T13:28:50-0700 [twisted.logger._observer#critical] Temporarily disabling observer <ims.application._eventsource.DataStoreEventSourceLogObserver object at 0x7f563eb60240> due to exception: [Failure instance: Traceback: <class 'TypeError'>: __init__() missing 1 required positional argument: 'retry'
	/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py:1212:_setIncidentAttribute
	/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py:966:_createAndAttachReportEntriesToIncident
	/opt/ims/lib/env/lib/python3.6/site-packages/twisted/logger/_logger.py:213:info
	/opt/ims/lib/env/lib/python3.6/site-packages/twisted/logger/_logger.py:135:emit
	--- <exception caught here> ---
	/opt/ims/lib/env/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
	/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_eventsource.py:208:__call__
	/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_eventsource.py:161:_transmogrify
	]
	Traceback (most recent call last):
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 1212, in _setIncidentAttribute
	    event, incidentNumber, (autoEntry,), cursor,
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 966, in _createAndAttachReportEntriesToIncident
	    reportEntries=reportEntries,
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/logger/_logger.py", line 213, in info
	    self.emit(LogLevel.info, format, **kwargs)
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/logger/_logger.py", line 135, in emit
	    self.observer(event)
	--- <exception caught here> ---
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
	    observer(event)
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_eventsource.py", line 208, in __call__
	    eventSourceEvent = self._transmogrify(event, self._counter)
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_eventsource.py", line 161, in _transmogrify
	    message=jsonTextFromObject(message),
	builtins.TypeError: __init__() missing 1 required positional argument: 'retry'
```

**Comment by wsanchez** [comment]
Fixed by #188
