### ISSUE TITLE
builtins.TypeError: __init__() missing 1 required positional argument: 'retry'

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#186]
```
2017-08-14T14:54:46-0700 [twisted.logger._observer#critical] Temporarily disabling observer <ims.application._eventsource.DataStoreEventSourceLogObserver object at 0x10eff79b0> due to exception: [Failure instance: Traceback: <class 'TypeError'>: __init__() missing 1 required positional argument: 'retry'
	/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/store/sqlite/_store.py:1122:_createIncident
	/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/store/sqlite/_store.py:966:_createAndAttachReportEntriesToIncident
	/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/logger/_logger.py:213:info
	/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/logger/_logger.py:135:emit
	--- <exception caught here> ---
	/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/logger/_observer.py:131:__call__
	/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/application/_eventsource.py:208:__call__
	/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/application/_eventsource.py:161:_transmogrify
	]
	Traceback (most recent call last):
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 1122, in _createIncident
	    incident.reportEntries, cursor,
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 966, in _createAndAttachReportEntriesToIncident
	    reportEntries=reportEntries,
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/logger/_logger.py", line 213, in info
	    self.emit(LogLevel.info, format, **kwargs)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/logger/_logger.py", line 135, in emit
	    self.observer(event)
	--- <exception caught here> ---
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/logger/_observer.py", line 131, in __call__
	    observer(event)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/application/_eventsource.py", line 208, in __call__
	    eventSourceEvent = self._transmogrify(event, self._counter)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/application/_eventsource.py", line 161, in _transmogrify
	    message=jsonTextFromObject(message),
	builtins.TypeError: __init__() missing 1 required positional argument: 'retry'
```

**Comment by wsanchez** [comment]
Dup of #185, whoops
