### ISSUE TITLE
exceptions.ValueError: Radial hour must be 1-12

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#19]
Seen in 2015 logs, apparently related to incident 986:

```
2015-09-04 13:53:46-0700 [-] Internal error
        Traceback (most recent call last):
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/klein/app.py", line 100, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/klein/app.py", line 185, in _f
            return _call(instance, f, request, *a, **kw)
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/klein/app.py", line 29, in _call
            return f(instance, *args, **kwargs)
          File "/home/ranger/ranger-ims-server/ims/sauce.py", line 145, in wrapper
            d = maybeDeferred(f, self, request, *args, **kwargs)
        --- <exception caught here> ---
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/ranger/ranger-ims-server/ims/protocol.py", line 718, in queue_incident
            edits = edits_from_query(author, number, request)
          File "/home/ranger/ranger-ims-server/ims/element/util.py", line 172, in edits_from_query
            description=location_description,
          File "/home/ranger/ranger-ims-server/ims/data.py", line 713, in __init__
            raise ValueError("Radial hour must be 1-12")
        exceptions.ValueError: Radial hour must be 1-12
```

**Comment by wsanchez** [comment]
This validation moved out of `__init__`.  Unclear if there's an underlying problem which will find a new way to annoy, but I don't think this is actionable at present, so punting.
