### ISSUE TITLE
exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#20]
See in 2015 logs, possibly related to incident 1443:

```
2015-09-07 01:50:34-0700 [-] Internal error
        Traceback (most recent call last):
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/klein/app.py", line 100, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/klein/app.py", line 185, in _f
            return _call(instance, f, request, *a, **kw)
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/klein/app.py", line 29, in _call
            return f(instance, *args, **kwargs)
          File "/home/ranger/ranger-ims-server/ims/sauce.py", line 145, in wrapper
            d = maybeDeferred(f, self, request, *args, **kwargs)
        --- <exception caught here> ---
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/ranger/ranger-ims-server/ims/protocol.py", line 585, in edit_incident
            d = self.data_incident_edit(number, request.content, self.user)
          File "/home/ranger/ranger-ims-server/ims/protocol.py", line 598, in data_incident_edit
            edited = edit_incident(incident, edits, author)
          File "/home/ranger/ranger-ims-server/ims/edit.py", line 192, in edit_incident
            old_location.address, new_location.address, "location address"
          File "/home/ranger/ranger-ims-server/ims/edit.py", line 93, in edit_value
            value=(describe(new_value) if new_value else u"<no value>")
        exceptions.UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
```

**Comment by wsanchez** [comment]
The deserialization in `editIncident` was substantially re-worked, so this code no longer exists as such.
