### ISSUE TITLE
builtins.AttributeError: 'NoneType' object has no attribute 'rangerHandle'

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#207]
Seen in logs:

```
2017-09-17T18:55:33-0700 [ims.application._klein#critical] Request failed
	Traceback (most recent call last):
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 126, in execute_endpoint
	    return endpoint_f(self._instance, *args, **kwargs)
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 211, in _f
	    return _call(instance, f, request, *a, **kw)
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 51, in _call
	    result = ensureDeferred(result)
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 908, in ensureDeferred
	    return _inlineCallbacks(None, coro, Deferred())
	--- <exception caught here> ---
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
	    result = g.send(result)
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_web.py", line 281, in viewIncidentReportPage
	    request, incidentReport
	  File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/auth/_provider.py", line 273, in authorizeRequestForIncidentReport
	    rangerHandle = request.user.rangerHandle
	builtins.AttributeError: 'NoneType' object has no attribute 'rangerHandle'
```

**Comment by wsanchez** [comment]
d71b8c05a8d081a520b7c40c132af85599f77ea8
