### ISSUE TITLE
ims.store._exceptions.StorageError: UNIQUE constraint failed: EVENT_ACCESS.EVENT, EVENT_ACCESS.EXPRESSION

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#208]
Seen in logs:

```
2017-09-10T04:27:46-0700 [ims.store.sqlite._store.DataStore#critical] Unable to set read access for 2017: UNIQUE constraint failed: EVENT_ACCESS.EVENT, EVENT_ACCESS.EXPRESSION
2017-09-10T04:27:46-0700 [ims.application._klein#critical] Request failed
        Traceback (most recent call last):
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 126, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 211, in _f
            return _call(instance, f, request, *a, **kw)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 51, in _call
            result = ensureDeferred(result)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 908, in ensureDeferred
            return _inlineCallbacks(None, coro, Deferred())
        --- <exception caught here> ---
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_api.py", line 876, in editAdminAccessResource
            await store.setReaders(event, acl["readers"])
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 420, in setReaders
            return self._setEventAccess(event, "read", readers)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 384, in _setEventAccess
            raise StorageError(e)
        ims.store._exceptions.StorageError: UNIQUE constraint failed: EVENT_ACCESS.EVENT, EVENT_ACCESS.EXPRESSION
```

**Comment by wsanchez** [comment]
This happens when you try to add an ACL entry that already exists, possibly in a different permission group

**Comment by wsanchez** [comment]
f41ddf9ee792ac095664327559aaf1a5ce571df2 fixes the data store not to raise

**Comment by wsanchez** [comment]
a615b0b800080ab8b52e992f5ae35575aab4f0da fixes the JavaScript client to show all changes to an event ACL
