### ISSUE TITLE
builtins.ValueError: one or more reserved delimiters &# present in query parameter value

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#209]
Seen in logs:

```
2017-09-11T06:50:23-0700 [ims.application._klein#critical] Request failed
        Traceback (most recent call last):
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/resource.py", line 264, in processing_failed
            return processing_failed(failure, error_handlers[1:])
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/resource.py", line 264, in processing_failed
            return processing_failed(failure, error_handlers[1:])
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/resource.py", line 260, in processing_failed
            failure)
        --- <exception caught here> ---
          File "/opt/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 133, in execute_error_handler
            return handler(self._instance, request, failure)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 323, in _f
            r = _call(instance, f, request, failure)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 48, in _call
            result = f(instance, *args, **kwargs)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_klein.py", line 69, in wrapper
            response = f(self, request, *args, **kwargs)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_klein.py", line 383, in notAuthenticatedError
            element = redirect(request, URLs.login, origin="o")
          File "/opt/ims/lib/env/lib/python3.6/site-packages/ims/application/_klein.py", line 86, in redirect
            location = location.set(origin, request.uri.decode("utf-8"))
          File "/opt/ims/lib/env/lib/python3.6/site-packages/hyperlink/_url.py", line 1294, in set
            return self.replace(query=q)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/hyperlink/_url.py", line 901, in replace
            uses_netloc=_optional(uses_netloc, self.uses_netloc)
          File "/opt/ims/lib/env/lib/python3.6/site-packages/hyperlink/_url.py", line 662, in __init__
            for (k, v) in query
          File "/opt/ims/lib/env/lib/python3.6/site-packages/hyperlink/_url.py", line 662, in <genexpr>
            for (k, v) in query
          File "/opt/ims/lib/env/lib/python3.6/site-packages/hyperlink/_url.py", line 430, in _textcheck
            % (''.join(delims), name, value))
        builtins.ValueError: one or more reserved delimiters &# present in query parameter value: '/ims/login?o=%2Fims%2Fims%2Fims%2Flogo.png&kwIV%3D9530%20AND%201%3D1%20UNION%20ALL%20SELECT%201%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%20FROM%20information_schema.tables%20WHERE%202%3E1--%2F%2A%2A%2F%3B%20EXEC%20xp_cmdshell%28%\
27cat%20..%2F..%2F..%2Fetc%2Fpasswd%27%29%23'

2017-09-11T06:50:23-0700 [ims.application._klein#critical] Internal error for resource: b'/ims/login?o=%2Fims%2Fims%2Fims%2Flogo.png&kwIV%3D9530%20AND%201%3D1%20UNION%20ALL%20SELECT%201%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%20FROM%20information_schema.tables%20WHERE%202%3E1--%2F%2A%2A%2F%3B%20EXEC%20xp_cmdshell%28%27cat%20.\
.%2F..%2F..%2Fetc%2Fpasswd%27%29%23': None
```

**Comment by wsanchez** [comment]
This is clearly some HAXXOR scanning of the site looking for a SQL injection.

So… not likely to cause any issues for someone using the app, but the exception should be caught.

**Comment by wsanchez** [comment]
5439caa95cbb0cbb5af776d34d58e369300329d1
