### ISSUE TITLE
exceptions.AttributeError: 'DutyManagementSystem' object has no attribute '_personnel'

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#21]
Seen in 2015 logs:

```
2015-09-08 16:18:26-0700 [-] Internal error
        Traceback (most recent call last):
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
            result = f(*args, **kw)
          File "/home/ranger/ranger-ims-server/ims/protocol.py", line 277, in list_personnel
            d = self.data_personnel()
          File "/home/ranger/ranger-ims-server/ims/protocol.py", line 292, in data_personnel
            d = self.dms.personnel()
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/ranger/ranger-ims-server/.develop/virtualenv/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/home/ranger/ranger-ims-server/ims/dms.py", line 186, in personnel
            returnValue(self._personnel)
        exceptions.AttributeError: 'DutyManagementSystem' object has no attribute '_personnel'
```

This may have been while the Clubhouse (DMS) switched hostnames.

**Comment by wsanchez** [comment]
69eb6c46f046f752369c5d66f376e0c214fe6d29
