### ISSUE TITLE
ims.store._exceptions.NoSuchIncidentReportError: No incident report #382

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#210]
Seen in logs:

```
2017-08-29T05:39:25-0700 [ims.application._klein#critical] Request failed
        Traceback (most recent call last):
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 126, in execute_endpoint
            return endpoint_f(self._instance, *args, **kwargs)
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 211, in _f
            return _call(instance, f, request, *a, **kw)
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/klein/app.py", line 51, in _call
            result = ensureDeferred(result)
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 908, in ensureDeferred
            return _inlineCallbacks(None, coro, Deferred())
        --- <exception caught here> ---
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
            result = g.send(result)
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/ims/application/_web.py", line 277, in viewIncidentReportPage
            numberValue
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 1660, in incidentReportWithNumber
            return self._fetchIncidentReport(number, cursor)
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 1575, in _fetchIncidentReport
            notFound()
          File "/usr/local/ims/lib/env/lib/python3.6/site-packages/ims/store/sqlite/_store.py", line 1565, in notFound
            f"No incident report #{incidentReportNumber}"
        ims.store._exceptions.NoSuchIncidentReportError: No incident report #382

2017-08-29T05:39:25-0700 [ims.application._klein#critical] Internal error for resource: b'/ims/app/incident_reports/382': None
2017-08-29T05:39:25-0700 [twisted.python.log#info] "100.93.88.167 > 127.0.0.1" Sir JayJay - [29/Aug/2017:12:39:24 +0000] "GET /ims/app/incident_reports/382 HTTP/1.1" 500 14 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
```

Client should have gotten a `404`, not a `500`.

**Comment by wsanchez** [comment]
073b973e22377cf97079e58fac5fa1c2708579e1
