### ISSUE TITLE
New incident error: 'int' object has no attribute 'splitlines'

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#273]
Create a new incident, add some text in the summary field, tab out of the field, and:

```console
2019-05-28T15:04:40-0700 [ims.application._api.APIApplication#info] User Tool created new incident #2 via JSON
2019-05-28T15:04:40-0700 [ims.application._klein#critical] Request failed
	Traceback (most recent call last):
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/klein/app.py", line 227, in _f
	    return _call(instance, f, request, *a, **kw)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/klein/app.py", line 52, in _call
	    result = ensureDeferred(result)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/internet/defer.py", line 911, in ensureDeferred
	    return _cancellableInlineCallbacks(coro)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/ims/application/_api.py", line 434, in newIncidentResource
	    request.setHeader("Incident-Number", incident.number)
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/web/http.py", line 1271, in setHeader
	    self.responseHeaders.setRawHeaders(name, [value])
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
	    for v in self._encodeValues(values)]
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/web/http_headers.py", line 220, in <listcomp>
	    for v in self._encodeValues(values)]
	  File "/Users/wsanchez/Dropbox/Developer/BurningMan/ranger-ims-server/.tox/run/lib/python3.6/site-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
	    return b' '.join(headerComponent.splitlines())
	builtins.AttributeError: 'int' object has no attribute 'splitlines'
```

**Comment by wsanchez** [comment]
Fixed by 7c7c3db6547d4c15a2ff061881a91c5c7b086091
