### ISSUE TITLE
Tests failing: AttributeError: 'unicode' object has no attribute 'description'

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#32]
```
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 104, in test_locationNoopName
    Location(u"Tokyo", u"9 & C"), Location(None, u"9 & C")
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 313, in assertEditValueNoop
    attribute, old_value, new_value
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 417, in editIncident
    u"Tool"
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/edit.py", line 233, in editIncident
    oldAddress.description, newAddress.description,
exceptions.AttributeError: 'unicode' object has no attribute 'description'

ims.service.test.test_edit.EditingTests.test_locationNoopName
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 169, in test_locationChangedNameAddress
    Location(u"Berlin", u"3 & C")
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 417, in editIncident
    u"Tool"
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/edit.py", line 233, in editIncident
    oldAddress.description, newAddress.description,
exceptions.AttributeError: 'unicode' object has no attribute 'description'

ims.service.test.test_edit.EditingTests.test_locationChangedNameAddress
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 152, in test_locationChangedAddress
    Location(None, u"3 & C")
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 417, in editIncident
    u"Tool"
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/edit.py", line 233, in editIncident
    oldAddress.description, newAddress.description,
exceptions.AttributeError: 'unicode' object has no attribute 'description'

ims.service.test.test_edit.EditingTests.test_locationChangedAddress
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 124, in test_locationSame
    Location(u"Tokyo", u"9 & C"), Location(u"Tokyo", u"9 & C")
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 313, in assertEditValueNoop
    attribute, old_value, new_value
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/service/test/test_edit.py", line 417, in editIncident
    u"Tool"
  File "/Users/wsanchez/Developer/BurningMan/ranger-ims-server/ims/edit.py", line 233, in editIncident
    oldAddress.description, newAddress.description,
exceptions.AttributeError: 'unicode' object has no attribute 'description'

ims.service.test.test_edit.EditingTests.test_locationSame
-------------------------------------------------------------------------------
```

**Comment by wsanchez** [comment]
d0ab1fd3d83df855c4ac9911f462b931d18842c2
