### ISSUE TITLE
Download of external resources is failing due to missing SSL module

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#380]
Seen on staging server:

```console
2020-03-20T17:55:07+0000 [ims.application._external.ExternalApplication#critical] Download failed for https://github.com/twbs/bootstrap/releases/download/v3.3.7/bootstrap-3.3.7-dist.zip: Error loading shared library libssl.so.47: No such file or directory (needed by /opt/ims/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so)
	Traceback (most recent call last):
	  File "/opt/ims/lib/python3.7/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	  File "/opt/ims/lib/python3.7/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/opt/ims/lib/python3.7/site-packages/ims/application/_external.py", line 120, in bootstrapResource
	    *names,
	  File "/opt/ims/lib/python3.7/site-packages/ims/application/_external.py", line 254, in cachedZippedResource
	    archivePath = await self.cacheFromURL(url, f"{archiveName}.zip")
	--- <exception caught here> ---
	  File "/opt/ims/lib/python3.7/site-packages/ims/application/_external.py", line 209, in cacheFromURL
	    await downloadPage(url.asText().encode("utf-8"), tmp)
	  File "/opt/ims/lib/python3.7/site-packages/twisted/python/deprecate.py", line 301, in deprecatedFunction
	    return function(*args, **kwargs)
	  File "/opt/ims/lib/python3.7/site-packages/twisted/web/client.py", line 814, in downloadPage
	    *args, **kwargs).deferred
	  File "/opt/ims/lib/python3.7/site-packages/twisted/web/client.py", line 745, in _makeGetterFactory
	    from twisted.internet import ssl
	  File "/opt/ims/lib/python3.7/site-packages/twisted/internet/ssl.py", line 59, in <module>
	    from OpenSSL import SSL
	  File "/opt/ims/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
	    from OpenSSL import crypto, SSL
	  File "/opt/ims/lib/python3.7/site-packages/OpenSSL/crypto.py", line 15, in <module>
	    from OpenSSL._util import (
	  File "/opt/ims/lib/python3.7/site-packages/OpenSSL/_util.py", line 6, in <module>
	    from cryptography.hazmat.bindings.openssl.binding import Binding
	  File "/opt/ims/lib/python3.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module>
	    from cryptography.hazmat.bindings._openssl import ffi, lib
	builtins.ImportError: Error loading shared library libssl.so.47: No such file or directory (needed by /opt/ims/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so)
	
2020-03-20T17:55:07+0000 [ims.application._external.ExternalApplication#critical] Unable to open zip archive /srv/ims/data/cache/bootstrap-3.3.7-dist.zip: [Errno 2] No such file or directory: '/srv/ims/data/cache/bootstrap-3.3.7-dist.zip'
2020-03-20T17:55:07+0000 [twisted.python.log#info] "24.6.151.7 > 172.31.61.192" - - [20/Mar/2020:17:55:06 +0000] "GET /ims/ext/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 9 "https://ranger-ims-staging.burningman.org/ims/app/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15"
```

**Comment by wsanchez** [comment]
Reproducible locally with Docker.
