### ISSUE TITLE
'RangerUser' object has no attribute 'rangerHandle'

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#468]
```console
Traceback (most recent call last):
File "/opt/ims/lib/python3.9/site-packages/twisted/internet/defer.py", line 460, in callback
self._startRunCallbacks(result)
File "/opt/ims/lib/python3.9/site-packages/twisted/internet/defer.py", line 568, in _startRunCallbacks
self._runCallbacks()
File "/opt/ims/lib/python3.9/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
current.result = callback(current.result, *args, **kw)
File "/opt/ims/lib/python3.9/site-packages/twisted/internet/defer.py", line 1475, in gotResult
_inlineCallbacks(r, g, status)
--- <exception caught here> ---
File "/opt/ims/lib/python3.9/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
result = g.send(result)
File "/opt/ims/lib/python3.9/site-packages/ims/application/_api.py", line 800, in readIncidentReportResource
await self.config.authProvider.authorizeRequestForIncidentReport(
File "/opt/ims/lib/python3.9/site-packages/ims/auth/_provider.py", line 222, in authorizeRequestForIncidentReport
rangerHandle = request.user.rangerHandle
builtins.AttributeError: 'RangerUser' object has no attribute 'rangerHandle'
```

**Comment by wsanchez** [comment]
Fixed in https://github.com/burningmantech/ranger-ims-server/commit/d7b9710f429cefc8cb969e2d53299efe486f896e
