### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-ims-server#62]
This should be logged without a traceback:
```
2016-06-22T13:08:40-0700 [ims.dms._dms.DutyManagementSystem#info] Retrieving personnel from Duty Management System...
2016-06-22T13:08:40-0700 [_GenericHTTPChannelProtocol,226,127.0.0.1] Rollback failed
	Traceback (most recent call last):
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/threadpool.py", line 246, in inContext
	    result = inContext.theWork()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/enterprise/adbapi.py", line 474, in _runInteraction
	    conn.rollback()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/enterprise/adbapi.py", line 52, in rollback
	    self._connection.rollback()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/pymysql/connections.py", line 771, in rollback
	    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/pymysql/connections.py", line 1054, in _execute_command
	    self._write_bytes(packet)
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/pymysql/connections.py", line 1006, in _write_bytes
	    raise err.OperationalError(2006, "MySQL server has gone away (%r)" % (e,))
	pymysql.err.OperationalError: (2006, "MySQL server has gone away (error(32, 'Broken pipe'))")
	
2016-06-22T13:08:40-0700 [ims.dms._dms.DutyManagementSystem#warn] Unable to load personnel data from DMS: (2013, 'Lost connection to MySQL server during query')
```

The server in this case is using an SSH tunnel to connect to MySQL, and that probably hiccuped, so unlikely to be common in prod.

And this isn't a big deal, since the user shouldn't be seeing an error; just means the we didn't refresh the cache this time but will try again.

**Comment by wsanchez** [comment]
Seen, also, I think related:
```
2016-06-24T10:04:34-0700 [ims.dms._dms.DutyManagementSystem#info] Retrieving personnel from Duty Management System...
2016-06-24T10:04:34-0700 [_GenericHTTPChannelProtocol,725,127.0.0.1] Rollback failed
	Traceback (most recent call last):
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/threadpool.py", line 246, in inContext
	    result = inContext.theWork()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	--- <exception caught here> ---
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/enterprise/adbapi.py", line 474, in _runInteraction
	    conn.rollback()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/twisted/enterprise/adbapi.py", line 52, in rollback
	    self._connection.rollback()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/pymysql/connections.py", line 772, in rollback
	    self._read_ok_packet()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/pymysql/connections.py", line 746, in _read_ok_packet
	    pkt = self._read_packet()
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/pymysql/connections.py", line 961, in _read_packet
	    packet_header = self._read_bytes(4)
	  File "/home/ims/ranger-ims-server/.develop/virtualenv/site-packages/pymysql/connections.py", line 998, in _read_bytes
	    2013, "Lost connection to MySQL server during query")
	pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')
```

**Comment by srabraham** [comment]
I'm curious to see the logs from recent years to see if this issue is still happening (or if other exceptions are getting raised)
